comparisons:
  mock_vs_condition1:
    nht:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition1_1
        - condition1_2
    someBait:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition1_1
        - condition1_2
  mock_vs_condition2:
    nht:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition2_1
        - condition2_2      
    someBait:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition2_1
        - condition2_2    
  condition1_vs_condition2:
    nht:
      control:
        - condition1_1
        - condition1_2
      treatment:
        - condition2_1
        - condition2_2
    someBait:
      control:
        - condition1_1
        - condition1_2
      treatment:
        - condition2_1
        - condition2_2

samples:
  someBait:
    mock_1: /from/root/4C/raw_data/mock_1.fastq
    mock_2: /from/root/4C/raw_data/mock_2.fastq
    condition1_1: /from/root/4C/raw_data/condition1_1.fastq
    condition1_2: /from/root/4C/raw_data/condition1_2.fastq
    condition2_1: /from/root/4C/raw_data/condition2_1.fastq
    condition2_2: /from/root/4C/raw_data/condition2_2.fastq
    
  nht:
    mock_1: /from/root/4C/raw_data/mock_1.fastq
    mock_2: /from/root/4C/raw_data/mock_2.fastq
    condition1_1: /from/root/4C/raw_data/condition1_1.fastq
    condition1_2: /from/root/4C/raw_data/condition1_2.fastq
    condition2_1: /from/root/4C/raw_data/condition2_1.fastq
    condition2_2: /from/root/4C/raw_data/condition2_2.fastq

baits:
  someBait:    
    bait_chr: chr2L
    bait_coord: 1234567
    bait_name: someBait
    primary_enz: AAGCTT
    species: dm
    primary_enz_name: hindiii
    reduced_genome: dm6
    fragment_len: 37
    primer: ACACCCGGTGTGTGTGTGTGTG
  
  nht:
    bait_chr: chr2L
    bait_coord: 1234567
    bait_name: someBait
    primary_enz: AAGCTT
    species: dm
    primary_enz_name: hindiii
    reduced_genome: dm6
    fragment_len: 37
    primer: ACACCCGGTGTGTGTGTGTGTG
