comparisons:
  mock_vs_condition1:
    nht:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition1_1
        - condition1_2
    someBait:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition1_1
        - condition1_2
  mock_vs_condition2:
    nht:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition2_1
        - condition2_2      
    someBait:
      control:
        - mock_1
        - mock_2
      treatment:
        - condition2_1
        - condition2_2    
  condition1_vs_condition2:
    nht:
      control:
        - condition1_1
        - condition1_2
      treatment:
        - condition2_1
        - condition2_2
    someBait:
      control:
        - condition1_1
        - condition1_2
      treatment:
        - condition2_1
        - condition2_2

samples:
  someBait:
    mock_1: /from/dir/location/raw_data/mock_1.fastq
    mock_2: /from/dir/location/raw_data/mock_2.fastq
    condition1_1: /from/dir/location/raw_data/condition1_1.fasta
    condition1_2: /from/dir/location/raw_data/condition1_2.fasta
    condition2_1: /from/dir/location/raw_data/condition2_1.fasta
    condition2_2: /from/dir/location/raw_data/condition2_2.fasta
    
  nht:
    mock_1: /from/dir/location/raw_data/mock_1.fastq
    mock_2: /from/dir/location/raw_data/mock_2.fastq
    condition1_1: /from/dir/location/raw_data/condition1_1.fasta
    condition1_2: /from/dir/location/raw_data/condition1_2.fasta
    condition2_1: /from/dir/location/raw_data/condition2_1.fasta
    condition2_2: /from/dir/location/raw_data/condition2_2.fasta

baits:
  someBait:    
    bait_chr: chr2L
    bait_coord: 1234567
    bait_name: someBait
    primary_enz: AAGCTT
    primary_enz_name: hindiii
    fragment_len: 37
    primer: AGCTGTA
  
  nht:
    bait_chr: chr2L
    bait_coord: 1234567
    bait_name: nht
    primary_enz: AAGCTT
    primary_enz_name: hindiii
    fragment_len: 37
    primer: AGCTGTA
    
reference_genome:
  name: dm6
  location: reduced_genome/dm6.fa
  species: dm
  
