comparisons:
  mock_vs_condition1:
    - bedGraphs/condition1_1_aligned_rm_self_und.bedGraph
    - bedGraphs/condition1_2_aligned_rm_self_und.bedGraph
    - bedGraphs/mock_1_aligned_rm_self_und.bedGraph
    - bedGraphs/mock_2_aligned_rm_self_und.bedGraph
  mock_vs_condition2:
    - bedGraphs/condition2_1_aligned_rm_self_und.bedGraph
    - bedGraphs/condition2_2_aligned_rm_self_und.bedGraph
    - bedGraphs/mock_1_aligned_rm_self_und.bedGraph
    - bedGraphs/mock_2_aligned_rm_self_und.bedGraph
  condition1_vs_condition2:
    - bedGraphs/condition1_1_aligned_rm_self_und.bedGraph
    - bedGraphs/condition1_2_aligned_rm_self_und.bedGraph
    - bedGraphs/condition2_1_aligned_rm_self_und.bedGraph
    - bedGraphs/condition2_2_aligned_rm_self_und.bedGraph

samples:
   mock_1: /from/root/4C/raw_data/mock_1.fastq
   mock_2: /from/root/4C/raw_data/mock_2.fastq
   siAGO2_1: /from/root/4C/raw_data/condition1_1.fastq
   siAGO2_2: /from/root/4C/raw_data/condition1_2.fastq
   dsLamin_1: /from/root/4C/raw_data/condition2_1.fastq
   dsLamin_2: /from/root/4C/raw_data/condition2_2.fastq

other:
  bait_chr: chr2L
  bait_coord: 1234567
  bait_name: someBait
  primary_enz: AAGCTT
  species: dm
  primary_enz_name: hindiii
  reduced_genome: dm6
  fragment_len: 37
  primer: ACACCCGGTGTGTGTGTGTGTG
  
