comparisons:
  mock_vs_siAGO2:
    nht:
      control:
        - mock_1
        - mock_2
      treatment:
        - siAGO2_1
        - siAGO2_2
  mock_vs_dsLamin:
    nht:
      control:
        - mock_1
        - mock_2
      treatment:
        - dsLamin_1
        - dsLamin_2
  siAGO2_vs_dsLamin:
    nht:
      control:
        - siAGO2_1
        - siAGO2_2
      treatment:
        - dsLamin_1
        - dsLamin_2

samples:
  nht:
    mock_1: /data/Lei/4C/behram-4c/raw_data/mock_1.fastq
    mock_2: /data/Lei/4C/behram-4c/raw_data/mock_2.fastq
    siAGO2_1: /data/Lei/4C/behram-4c/raw_data/siAGO2_1.fastq
    siAGO2_2: /data/Lei/4C/behram-4c/raw_data/siAGO2_2.fastq
    dsLamin_1: /data/Lei/4C/behram-4c/raw_data/dsLamin_1.fastq
    dsLamin_2: /data/Lei/4C/behram-4c/raw_data/dsLamin_2.fastq
    
baits:
  nht:
    bait_chr: chr2L
    bait_coord: 15318925
    bait_name: nht
    primary_enz: AAGCTT
    primary_enz_name: hindiii
    fragment_len: 37
    primer: ACCGTTTTTGACAACAGCAGCTGTA
    
reference_genome:
  name: dm6
  location: reduced_genome/dm6.fa
  species: dm
  
differential_analysis:
  pval: 0.05
